import { 
  Business, 
  Goal, 
  StrategicMonth, 
  Project, 
  Task, 
  ScheduleBlock, 
  UserSettings, 
  ActivityLog, 
  ScheduleEntry, 
  ScheduleDayReview,
  GoogleConnection,
  GoogleTaskListMapping,
  GoogleTaskMapping,
  GoogleCalendarMapping,
  GoogleSyncLog
} from './types';

export const INITIAL_BUSINESSES: Business[] = [
  {
    id: 'biz-col',
    code: 'COL',
    name: 'Circle of Learning',
    tagline: 'Education & Institutional Scale',
    description: 'Notes, tests, institutional expansion, digital presence, and education engines.',
    color: '#3b82f6', // Blue
    iconName: 'GraduationCap',
    isActive: true,
  },
  {
    id: 'biz-designoia',
    code: 'DESIGNOIA',
    name: 'Designoia',
    tagline: 'Design Agency & Sales Engine',
    description: 'Digital presence, international outreach, premium client acquisition, and creative studio.',
    color: '#8b5cf6', // Purple
    iconName: 'Sparkles',
    isActive: true,
  },
  {
    id: 'biz-clikixpress',
    code: 'CLIKIXPRESS',
    name: 'Clikixpress',
    tagline: 'Ecommerce & Logistics Scale',
    description: 'Pvt Ltd entity, ecommerce platform, manufacturing, godowns, and fulfillment network.',
    color: '#f97316', // Orange
    iconName: 'Package',
    isActive: true,
  },
  {
    id: 'biz-personal',
    code: 'PERSONAL',
    name: 'Personal',
    tagline: 'Life, Assets & Well-being',
    description: 'Car, home, health, personal assets, and family milestones.',
    color: '#10b981', // Emerald
    iconName: 'User',
    isActive: true,
  },
];

export const INITIAL_GOALS: Goal[] = [
  // COL Goals
  {
    id: 'goal-col-1',
    businessCode: 'COL',
    title: '5 Physical Institutes',
    category: 'infrastructure',
    targetYear: 2029,
    targetMetric: '5 centers',
    currentMetric: '1 center developing',
    isCompleted: false,
  },
  {
    id: 'goal-col-2',
    businessCode: 'COL',
    title: '₹5 Lakh / Month Recurring Revenue',
    category: 'revenue',
    targetYear: 2028,
    targetMetric: '₹5,00,000 / mo',
    currentMetric: '₹0 / mo',
    isCompleted: false,
  },
  {
    id: 'goal-col-3',
    businessCode: 'COL',
    title: 'COL Digital Learning Platform & International Reach',
    category: 'scale',
    targetYear: 2028,
    targetMetric: 'Global enrolled students',
    currentMetric: 'Phase 1 development',
    isCompleted: false,
  },
  {
    id: 'goal-col-4',
    businessCode: 'COL',
    title: 'YouTube Channel: 100,000 Subscribers & Monetization',
    category: 'audience',
    targetYear: 2027,
    targetMetric: '100k subs + revenue',
    currentMetric: 'Channel setup',
    isCompleted: false,
  },

  // Designoia Goals
  {
    id: 'goal-des-1',
    businessCode: 'DESIGNOIA',
    title: 'High-Converting Digital Presence & Case Study Portfolio',
    category: 'system',
    targetYear: 2026,
    targetMetric: 'Active client pipeline',
    currentMetric: 'Portfolio development',
    isCompleted: false,
  },
  {
    id: 'goal-des-2',
    businessCode: 'DESIGNOIA',
    title: 'International Client Roster (US/UK/EU/Middle East)',
    category: 'revenue',
    targetYear: 2027,
    targetMetric: '5 recurring retainer clients',
    currentMetric: 'Prospect lists initiated',
    isCompleted: false,
  },
  {
    id: 'goal-des-3',
    businessCode: 'DESIGNOIA',
    title: 'Physical Creative Studio / Office in Noida / Gurgaon',
    category: 'infrastructure',
    targetYear: 2029,
    targetMetric: 'Dedicated office lease',
    currentMetric: 'Virtual',
    isCompleted: false,
  },
  {
    id: 'goal-des-4',
    businessCode: 'DESIGNOIA',
    title: 'Well-Trained Elite Creative & Growth Team',
    category: 'scale',
    targetYear: 2028,
    targetMetric: '6 full-time specialists',
    currentMetric: 'Solo founder',
    isCompleted: false,
  },

  // Clikixpress Goals
  {
    id: 'goal-clk-1',
    businessCode: 'CLIKIXPRESS',
    title: 'Incorporate Pvt Ltd Company & Regulatory Compliance',
    category: 'infrastructure',
    targetYear: 2027,
    targetMetric: 'Certificate of Incorporation',
    currentMetric: 'MSME registration',
    isCompleted: false,
  },
  {
    id: 'goal-clk-2',
    businessCode: 'CLIKIXPRESS',
    title: 'Proprietary Ecommerce Platform & Mobile App',
    category: 'system',
    targetYear: 2027,
    targetMetric: 'Web + iOS + Android live',
    currentMetric: 'Architecture phase',
    isCompleted: false,
  },
  {
    id: 'goal-clk-3',
    businessCode: 'CLIKIXPRESS',
    title: 'Owned Godowns, Warehouses & Dedicated Logistics Staff',
    category: 'infrastructure',
    targetYear: 2030,
    targetMetric: '2 fulfillment centers',
    currentMetric: 'Initial planning',
    isCompleted: false,
  },
  {
    id: 'goal-clk-4',
    businessCode: 'CLIKIXPRESS',
    title: 'In-House Manufacturing & Global Cross-Border Expansion',
    category: 'scale',
    targetYear: 2031,
    targetMetric: 'Global shipping active',
    currentMetric: 'Research',
    isCompleted: false,
  },

  // Personal Goals
  {
    id: 'goal-per-1',
    businessCode: 'PERSONAL',
    title: 'Acquire First Premium Car',
    category: 'personal',
    targetYear: 2028,
    targetMetric: 'Car purchased outright/comfortably financed',
    currentMetric: 'Savings plan',
    isCompleted: false,
  },
  {
    id: 'goal-per-2',
    businessCode: 'PERSONAL',
    title: 'Purchase Dream Home Property',
    category: 'personal',
    targetYear: 2030,
    targetMetric: 'Deed registration',
    currentMetric: 'Financial roadmap',
    isCompleted: false,
  },
  {
    id: 'goal-per-3',
    businessCode: 'PERSONAL',
    title: 'Full Financial Freedom & Exit School/Tuition Schedule',
    category: 'personal',
    targetYear: 2028,
    targetMetric: '100% full-time on ventures',
    currentMetric: 'Transitioning',
    isCompleted: false,
  },
];

export const INITIAL_STRATEGIC_MONTHS: StrategicMonth[] = [
  {
    id: 'm-2026-09',
    yearMonth: '2026-09',
    focusTitle: 'Foundation + Master Plan + Systems',
    targetOutcome: 'Complete core operational setup, notes upload pipeline, and initial n8n automation links.',
    kpis: ['CEO OS deployed & daily active', 'COL Notes 9th & 10th ready', 'FB & Pinterest workflows tested'],
    definitionOfDone: 'All foundational digital assets configured, daily 45-min execution habit established.',
    isCurrent: true,
  },
  {
    id: 'm-2026-10',
    yearMonth: '2026-10',
    focusTitle: 'Designoia Digital Presence',
    targetOutcome: 'Launch high-converting agency portfolio and initial offer packaging.',
    kpis: ['Designoia landing page live', '3 polished case studies published', 'Cold outreach list ready'],
    definitionOfDone: 'Live URL with client booking integration and tested submission flow.',
  },
  {
    id: 'm-2026-11',
    yearMonth: '2026-11',
    focusTitle: 'Designoia Sales Engine',
    targetOutcome: 'Initiate international outreach campaign and secure first consultation calls.',
    kpis: ['100 targeted DMs/emails sent', '5 discovery calls booked', '1 retainer proposal sent'],
    definitionOfDone: 'Sales outreach SOP tested and repeatable.',
  },
  {
    id: 'm-2026-12',
    yearMonth: '2026-12',
    focusTitle: 'COL Systems & Content Pipeline',
    targetOutcome: 'Standardize test generation, NCERT solutions, and content publishing workflow.',
    kpis: ['11th and 12th Notes uploaded', 'Automated test bank active', 'Video recording schedule set'],
    definitionOfDone: 'COL educational resources accessible and organized for distribution.',
  },
  {
    id: 'm-2027-01',
    yearMonth: '2027-01',
    focusTitle: 'Clikixpress MVP',
    targetOutcome: 'Define initial product catalogue, supplier terms, and web storefront prototype.',
    kpis: ['Product shortlist locked', 'Supplier agreements drafted', 'Shopify/custom storefront MVP ready'],
    definitionOfDone: 'First end-to-end test checkout successfully placed.',
  },
  {
    id: 'm-2027-02',
    yearMonth: '2027-02',
    focusTitle: 'Automation Month',
    targetOutcome: 'Link n8n workflows for lead nurturing, social auto-posting, and order routing.',
    kpis: ['Cross-platform posting active', 'Lead auto-capture to CRM', 'Alerts on high-priority inquiries'],
    definitionOfDone: 'Zero manual copy-pasting for inquiries and basic social distribution.',
  },
  {
    id: 'm-2027-03',
    yearMonth: '2027-03',
    focusTitle: 'Content Engine',
    targetOutcome: 'Launch YouTube educational channel and organic agency reels.',
    kpis: ['8 long-form videos published', '16 short-form reels', '1,000 subscribers reached'],
    definitionOfDone: 'Consistent weekly publishing cadence running.',
  },
  {
    id: 'm-2027-04',
    yearMonth: '2027-04',
    focusTitle: 'Team Foundation',
    targetOutcome: 'Hire first freelance editor / VA to delegate non-core tasks.',
    kpis: ['Job description published', 'Candidate hired & trained', 'SOP library created'],
    definitionOfDone: 'First 10 hours/week of routine work delegated.',
  },
  {
    id: 'm-2027-05',
    yearMonth: '2027-05',
    focusTitle: 'Revenue Push',
    targetOutcome: 'Target ₹1.5L/mo combined profit run-rate across active ventures.',
    kpis: ['Designoia monthly revenue > ₹1L', 'COL enrollments active', 'Clikixpress initial sales'],
    definitionOfDone: 'Clear cash flow buffer established in business account.',
  },
  {
    id: 'm-2027-06',
    yearMonth: '2027-06',
    focusTitle: 'Finance + Compliance',
    targetOutcome: 'Complete tax planning, GST filings, and formal accounting structure.',
    kpis: ['Chartered Accountant review', 'GST filing streamlined', 'Clean P&L dashboard'],
    definitionOfDone: 'All corporate filings up to date with zero compliance backlogs.',
  },
  {
    id: 'm-2027-07',
    yearMonth: '2027-07',
    focusTitle: 'Scale Readiness',
    targetOutcome: 'Stress-test infrastructure, server capacity, and fulfillment logistics.',
    kpis: ['Load test web services', 'Fulfillment turnaround < 48hrs', 'Customer satisfaction > 90%'],
    definitionOfDone: 'Ready to handle 5x user volume without breaking.',
  },
  {
    id: 'm-2027-08',
    yearMonth: '2027-08',
    focusTitle: 'Annual Review & Year 2 Strategy',
    targetOutcome: 'Comprehensive 360 review of Year 1 achievements and Year 2 calibration.',
    kpis: ['Annual targets vs actuals audited', '5-year vision refreshed', 'Year 2 roadmap approved'],
    definitionOfDone: 'Year 2 Q1-Q4 roadmap fully mapped in CEO OS.',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  // DESIGNOIA HIERARCHY
  // 1. Parent Project: Prorido
  {
    id: 'proj-prorido',
    code: 'P-001',
    name: 'Prorido',
    businessCode: 'DESIGNOIA',
    description: 'Flagship productized design and conversion optimization engine.',
    successDefinition: 'Prorido platform deployed, initial 3 clients onboarded, and streamlined delivery pipeline active.',
    status: 'ACTIVE',
    priority: 'P1',
    startDate: '2026-09-01',
    targetDate: '2026-11-30',
    createdAt: '2026-09-01T00:00:00Z',
  },
  // 1a. Sub-Project: Prorido Website
  {
    id: 'proj-prorido-web',
    code: 'P-001-A',
    name: 'Prorido Website',
    businessCode: 'DESIGNOIA',
    parentProjectId: 'proj-prorido',
    description: 'High-converting interactive landing page with case study showcase.',
    successDefinition: 'Website live on custom domain with sub-second load times and Calendly integration.',
    status: 'ACTIVE',
    priority: 'P1',
    startDate: '2026-09-01',
    targetDate: '2026-09-25',
    createdAt: '2026-09-01T00:00:00Z',
  },
  // 1b. Sub-Project: Prorido Product
  {
    id: 'proj-prorido-prod',
    code: 'P-001-B',
    name: 'Prorido Product',
    businessCode: 'DESIGNOIA',
    parentProjectId: 'proj-prorido',
    description: 'Design system templates, UI kits, and client delivery portal.',
    successDefinition: 'Standardized design library ready for rapid client project turnaround.',
    status: 'ACTIVE',
    priority: 'P2',
    startDate: '2026-09-15',
    targetDate: '2026-10-15',
    createdAt: '2026-09-01T00:00:00Z',
  },
  // 1c. Sub-Project: Prorido Launch
  {
    id: 'proj-prorido-launch',
    code: 'P-001-C',
    name: 'Prorido Launch',
    businessCode: 'DESIGNOIA',
    parentProjectId: 'proj-prorido',
    description: 'Product Hunt, LinkedIn, and international design community campaign.',
    successDefinition: 'Featured launch event, 500+ site visitors, and 5 demo requests.',
    status: 'ACTIVE',
    priority: 'P2',
    startDate: '2026-10-15',
    targetDate: '2026-11-15',
    createdAt: '2026-09-01T00:00:00Z',
  },
  // 2. Standalone Project: Designoia Website
  {
    id: 'proj-des-web',
    code: 'P-002',
    name: 'Designoia Website',
    businessCode: 'DESIGNOIA',
    description: 'Main agency digital presence and portfolio showcase.',
    successDefinition: 'Full agency site live with international inquiry routing and branding.',
    status: 'ACTIVE',
    priority: 'P1',
    startDate: '2026-09-10',
    targetDate: '2026-10-10',
    createdAt: '2026-09-01T00:00:00Z',
  },
  // 3. Standalone Project: International Sales
  {
    id: 'proj-des-sales',
    code: 'P-003',
    name: 'International Sales',
    businessCode: 'DESIGNOIA',
    description: 'Outbound sales engine targeting US, UK, and Middle East prospects.',
    successDefinition: '100 prospect list verified, customized outreach templates sent, 3 discovery calls booked.',
    status: 'ACTIVE',
    priority: 'P2',
    startDate: '2026-10-01',
    targetDate: '2026-11-30',
    createdAt: '2026-09-01T00:00:00Z',
  },

  // COL (Circle of Learning)
  {
    id: 'proj-col-auto',
    code: 'P-004',
    name: 'COL Automations',
    businessCode: 'COL',
    description: 'Social media, lead capture, and distribution workflows via n8n.',
    successDefinition: 'All required social media automation workflows (FB, Pinterest, YouTube) are connected and running.',
    status: 'ACTIVE',
    priority: 'P1',
    startDate: '2026-09-01',
    targetDate: '2026-09-30',
    createdAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'proj-col-notes',
    code: 'P-005',
    name: 'COL Notes',
    businessCode: 'COL',
    description: 'Curriculum-aligned study notes and digital downloads.',
    successDefinition: 'All required 9th, 10th, 11th, and 12th notes are cleanly formatted, converted to PDF, and uploaded.',
    status: 'ACTIVE',
    priority: 'P1',
    startDate: '2026-09-01',
    targetDate: '2026-09-25',
    createdAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'proj-col-tests',
    code: 'P-006',
    name: 'COL Tests',
    businessCode: 'COL',
    description: 'Chapter-wise and full mock test series.',
    successDefinition: 'Structured test papers and automated answer keys are created and proofread.',
    status: 'ACTIVE',
    priority: 'P2',
    startDate: '2026-09-15',
    targetDate: '2026-10-15',
    createdAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'proj-col-skills',
    code: 'P-007',
    name: 'Skill Courses',
    businessCode: 'COL',
    description: 'Practical vocational and digital skill mini-certifications.',
    successDefinition: 'Curriculum outline and pilot modules for first 2 high-demand skill courses recorded and uploaded.',
    status: 'ACTIVE',
    priority: 'P3',
    startDate: '2026-10-01',
    targetDate: '2026-10-31',
    createdAt: '2026-09-01T00:00:00Z',
  },

  // CLIKIXPRESS
  {
    id: 'proj-clk-mvp',
    code: 'P-008',
    name: 'MVP',
    businessCode: 'CLIKIXPRESS',
    description: 'Initial ecommerce storefront and product catalog setup.',
    successDefinition: 'First 20 SKUs live with payment gateway integration and order notification webhook.',
    status: 'ACTIVE',
    priority: 'P1',
    startDate: '2026-10-01',
    targetDate: '2026-11-15',
    createdAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'proj-clk-ecom',
    code: 'P-009',
    name: 'Ecommerce Platform',
    businessCode: 'CLIKIXPRESS',
    description: 'Custom scalable ecommerce engine and warehouse sync.',
    successDefinition: 'Full multi-vendor architecture and order tracking system live.',
    status: 'ACTIVE',
    priority: 'P2',
    startDate: '2026-11-01',
    targetDate: '2027-01-31',
    createdAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'proj-clk-ops',
    code: 'P-010',
    name: 'Operations',
    businessCode: 'CLIKIXPRESS',
    description: 'Courier partner agreements, packaging standards, and return workflow.',
    successDefinition: 'Standard operating procedures drafted and fulfillment partner SLA locked.',
    status: 'ACTIVE',
    priority: 'P2',
    startDate: '2026-11-15',
    targetDate: '2027-02-15',
    createdAt: '2026-09-01T00:00:00Z',
  },
];

export const INITIAL_TASKS: Task[] = [
  // 1. MUST-WIN TODAY (Linked to Google Tasks & Scheduled in Google Calendar)
  {
    id: 'task-prorido-home',
    code: 'T-001',
    title: 'Finish Prorido Homepage',
    businessCode: 'DESIGNOIA',
    projectId: 'proj-prorido-web',
    status: 'TODAY',
    priority: 'P1',
    isMustWin: true,
    estimatedMinutes: 45,
    scheduledDate: '2026-09-07',
    scheduledTime: '23:15',
    dueDate: '2026-09-07',
    notes: 'Implement hero section, live portfolio previews, and interactive conversion calculator.',
    rescueAction: 'Review homepage hero typography and test mobile responsive layout.',
    source: 'CEO_OS',
    externalTaskId: 'gtask-prorido-home-01',
    externalTaskListId: 'list-prorido',
    googleCalendarEventId: 'gcal-prorido-home-01',
    googleCalendarId: 'primary',
    googleEtag: '"etag-gtask-01"',
    syncStatus: 'SYNCED',
    lastSyncedAt: '2026-09-07T08:00:00Z',
    createdAt: '2026-09-05T10:00:00Z',
  },
  // Subtasks for Prorido Homepage
  {
    id: 'subtask-1',
    parentTaskId: 'task-prorido-home',
    title: 'Create homepage wireframe & layout structure',
    businessCode: 'DESIGNOIA',
    projectId: 'proj-prorido-web',
    status: 'DONE',
    priority: 'P1',
    estimatedMinutes: 15,
    completedAt: '2026-09-05T20:00:00Z',
    createdAt: '2026-09-05T10:05:00Z',
  },
  {
    id: 'subtask-2',
    parentTaskId: 'task-prorido-home',
    title: 'Build hero section with high-contrast typography',
    businessCode: 'DESIGNOIA',
    projectId: 'proj-prorido-web',
    status: 'DONE',
    priority: 'P1',
    estimatedMinutes: 15,
    completedAt: '2026-09-05T21:00:00Z',
    createdAt: '2026-09-05T10:10:00Z',
  },
  {
    id: 'subtask-3',
    parentTaskId: 'task-prorido-home',
    title: 'Build pricing & tier comparison section',
    businessCode: 'DESIGNOIA',
    projectId: 'proj-prorido-web',
    status: 'TODAY',
    priority: 'P1',
    estimatedMinutes: 15,
    createdAt: '2026-09-05T10:15:00Z',
  },
  {
    id: 'subtask-4',
    parentTaskId: 'task-prorido-home',
    title: 'Mobile responsiveness & touch optimization',
    businessCode: 'DESIGNOIA',
    projectId: 'proj-prorido-web',
    status: 'TODAY',
    priority: 'P1',
    estimatedMinutes: 10,
    createdAt: '2026-09-05T10:20:00Z',
  },

  // 2. IMPORTED FROM GOOGLE TASKS (Universal Capture Inbox)
  {
    id: 'task-gt-pagespeed',
    code: 'T-GT-01',
    title: 'Check Prorido PageSpeed',
    businessCode: 'DESIGNOIA',
    projectId: 'proj-prorido-web',
    status: 'INBOX',
    priority: 'P2',
    estimatedMinutes: 20,
    notes: 'Run Lighthouse mobile audit on deployed Vercel URL and check LCP score.',
    source: 'GOOGLE_TASKS',
    externalTaskId: 'gtask-pagespeed-02',
    externalTaskListId: 'list-prorido',
    googleEtag: '"etag-gtask-02"',
    syncStatus: 'SYNCED',
    lastSyncedAt: '2026-09-07T08:00:00Z',
    createdAt: '2026-09-07T07:45:00Z',
  },
  {
    id: 'task-gt-supplier-call',
    code: 'T-GT-02',
    title: 'Call supplier about packaging',
    businessCode: 'CLIKIXPRESS',
    projectId: 'proj-clk-mvp',
    status: 'INBOX',
    priority: 'P2',
    estimatedMinutes: 15,
    notes: 'Captured via Google Assistant on mobile.',
    source: 'GOOGLE_TASKS',
    externalTaskId: 'gtask-supplier-03',
    externalTaskListId: 'list-clikixpress',
    googleEtag: '"etag-gtask-03"',
    syncStatus: 'SYNCED',
    lastSyncedAt: '2026-09-07T08:00:00Z',
    createdAt: '2026-09-07T08:15:00Z',
  },

  // 3. OPTIONAL TASKS TODAY
  {
    id: 'task-col-pinterest',
    code: 'T-002',
    title: 'Connect Pinterest to n8n',
    businessCode: 'COL',
    projectId: 'proj-col-auto',
    status: 'TODAY',
    priority: 'P2',
    isMustWin: false,
    estimatedMinutes: 20,
    scheduledDate: '2026-09-07',
    notes: 'Configure Pinterest board token and automated pin creation node.',
    rescueAction: 'Log into Pinterest business account and copy board ID.',
    source: 'CEO_OS',
    externalTaskId: 'gtask-col-pinterest-04',
    externalTaskListId: 'list-col',
    syncStatus: 'SYNCED',
    lastSyncedAt: '2026-09-07T08:00:00Z',
    createdAt: '2026-09-05T10:25:00Z',
  },
  {
    id: 'task-col-9th',
    code: 'T-003',
    title: 'Prepare 9th Notes',
    businessCode: 'COL',
    projectId: 'proj-col-notes',
    status: 'TODAY',
    priority: 'P2',
    isMustWin: false,
    estimatedMinutes: 30,
    scheduledDate: '2026-09-07',
    notes: 'Compile Science & Math chapters 1-4 summaries.',
    rescueAction: 'Review Chapter 1 summary bullet points.',
    source: 'CEO_OS',
    externalTaskId: 'gtask-col-9th-05',
    externalTaskListId: 'list-col',
    syncStatus: 'SYNCED',
    lastSyncedAt: '2026-09-07T08:00:00Z',
    createdAt: '2026-09-05T10:30:00Z',
  },

  // 4. OVERDUE TASKS (DEMO / INITIAL)
  {
    id: 'task-col-fb',
    code: 'T-004',
    title: 'Connect FB to n8n',
    businessCode: 'COL',
    projectId: 'proj-col-auto',
    status: 'OVERDUE',
    priority: 'P1',
    estimatedMinutes: 30,
    scheduledDate: '2026-09-05',
    dueDate: '2026-09-05',
    notes: 'Verify OAuth permissions in Meta developer console.',
    rescueAction: 'Check FB developer token validity.',
    overdueAt: '2026-09-06T00:00:00Z',
    source: 'CEO_OS',
    syncStatus: 'SYNCED',
    createdAt: '2026-09-04T10:00:00Z',
  },
  {
    id: 'task-col-msme',
    code: 'T-005',
    title: 'MSME Registration Verification',
    businessCode: 'COL',
    projectId: 'proj-col-auto',
    status: 'OVERDUE',
    priority: 'P2',
    estimatedMinutes: 25,
    scheduledDate: '2026-09-04',
    dueDate: '2026-09-04',
    notes: 'Submit certificate copy for portal verification.',
    rescueAction: 'Check Udyam registration PDF download.',
    overdueAt: '2026-09-05T00:00:00Z',
    source: 'CEO_OS',
    syncStatus: 'SYNCED',
    createdAt: '2026-09-03T10:00:00Z',
  },

  // 5. THIS WEEK
  {
    id: 'task-col-10th',
    code: 'T-006',
    title: 'Finish 10th Notes',
    businessCode: 'COL',
    projectId: 'proj-col-notes',
    status: 'THIS_WEEK',
    priority: 'P1',
    estimatedMinutes: 45,
    notes: 'Export PDF, verify formula formatting in Physics & Chemistry chapters.',
    rescueAction: 'Check formatting on first 5 pages.',
    source: 'CEO_OS',
    syncStatus: 'SYNCED',
    createdAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'task-des-case-study',
    code: 'T-007',
    title: 'Publish 2 Designoia Case Studies',
    businessCode: 'DESIGNOIA',
    projectId: 'proj-des-web',
    status: 'THIS_WEEK',
    priority: 'P2',
    estimatedMinutes: 45,
    notes: 'Format screenshots and write conversion metrics summaries.',
    rescueAction: 'Export 4 mockup images.',
    source: 'CEO_OS',
    syncStatus: 'SYNCED',
    createdAt: '2026-09-02T10:00:00Z',
  },

  // 6. NEXT / BACKLOG
  {
    id: 'task-clk-supplier',
    code: 'T-008',
    title: 'Lock First 5 Clikixpress Suppliers',
    businessCode: 'CLIKIXPRESS',
    projectId: 'proj-clk-mvp',
    status: 'NEXT',
    priority: 'P2',
    estimatedMinutes: 60,
    notes: 'Compare wholesale quotation rates and shipping turnaround times.',
    rescueAction: 'Review supplier WhatsApp quotes.',
    source: 'CEO_OS',
    syncStatus: 'SYNCED',
    createdAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'task-col-jee',
    code: 'T-009',
    title: 'JEE Mock Test Series 1',
    businessCode: 'COL',
    projectId: 'proj-col-tests',
    status: 'NEXT',
    priority: 'P3',
    estimatedMinutes: 60,
    notes: 'Format 30-question Physics mock test.',
    rescueAction: 'Draft 5 questions.',
    source: 'CEO_OS',
    syncStatus: 'SYNCED',
    createdAt: '2026-09-01T10:00:00Z',
  },
];

export const INITIAL_SCHEDULE_BLOCKS: ScheduleBlock[] = [
  {
    id: 'sched-1',
    name: 'School / MIS / Admin',
    startTime: '08:00',
    endTime: '16:00',
    category: 'SCHOOL',
    daysOfWeek: [1, 2, 3, 4, 5, 6],
    isCeoTime: false,
    description: 'Day job responsibilities, MIS coordination, and administration.',
  },
  {
    id: 'sched-2',
    name: 'Tuition Classes',
    startTime: '16:00',
    endTime: '19:00',
    category: 'TUITION',
    daysOfWeek: [1, 2, 3, 4, 5, 6],
    isCeoTime: false,
    description: 'Daily batch teaching: Physics, Math, and Chemistry.',
  },
  {
    id: 'sched-3',
    name: 'Classes / Commute',
    startTime: '19:00',
    endTime: '22:30',
    category: 'CLASSES',
    daysOfWeek: [1, 2, 3, 4, 5, 6],
    isCeoTime: false,
    description: 'Advanced batches, student assessments, travel.',
  },
  {
    id: 'sched-4',
    name: 'Dinner & Buffer',
    startTime: '22:30',
    endTime: '23:15',
    category: 'REST',
    daysOfWeek: [1, 2, 3, 4, 5, 6, 7],
    isCeoTime: false,
    description: 'Dinner, rest, transition to CEO headspace.',
  },
  {
    id: 'sched-5',
    name: '🚀 CEO Work Block',
    startTime: '23:15',
    endTime: '00:00',
    category: 'CEO_BLOCK',
    daysOfWeek: [1, 2, 3, 4, 5, 6, 7],
    isCeoTime: true,
    description: '30-45 minutes of laser-focused business building & execution.',
  },
];

export const INITIAL_SETTINGS: UserSettings = {
  userName: 'Founder',
  theme: 'dark',
  timezone: 'Asia/Kolkata',
  dailyWorkCapacityMinutes: 45,
  morningNotificationTime: '07:30',
  ceoBlockStart: '23:15',
  ceoBlockEnd: '00:00',
  defaultWorkDuration: 45,
  rescueModeDuration: 10,
  notificationsEnabled: true,
  audioChimeEnabled: true,
  lastActiveDate: '2026-09-07',
  lastMustWinId: 'task-prorido-home',
  yesterdayMustWinCompleted: false,
  onboardingCompleted: true,

  // Google Sync Preferences
  googleAutoSyncOnOpen: true,
  googleDeleteMode: 'ASK',
  conflictResolutionStrategy: 'KEEP_CEO_OS',
};

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'act-1',
    entityType: 'TASK',
    entityId: 'subtask-1',
    title: 'Create homepage wireframe & layout structure',
    action: 'COMPLETED',
    details: 'Subtask finished under Prorido Homepage',
    createdAt: '2026-09-05T20:00:00Z',
  },
  {
    id: 'act-2',
    entityType: 'TASK',
    entityId: 'subtask-2',
    title: 'Build hero section with high-contrast typography',
    action: 'COMPLETED',
    details: 'Subtask finished under Prorido Homepage',
    createdAt: '2026-09-05T21:00:00Z',
  },
  {
    id: 'act-3',
    entityType: 'TASK',
    entityId: 'task-col-fb',
    title: 'Connect FB to n8n',
    action: 'ROLLED_OVER',
    details: 'Unfinished task transitioned: TODAY → OVERDUE',
    createdAt: '2026-09-06T00:00:00Z',
  },
  {
    id: 'act-4',
    entityType: 'TASK',
    entityId: 'task-prorido-home',
    title: 'Finish Prorido Homepage',
    action: 'MUST_WIN_SET',
    details: 'Selected as Today\'s Primary Must-Win',
    createdAt: '2026-09-06T00:01:00Z',
  },
];

export const INITIAL_SCHEDULE_ENTRIES: ScheduleEntry[] = [
  // Today's entries (2026-09-07)
  {
    id: 'entry-today-1',
    date: '2026-09-07',
    plannedStartTime: '08:00',
    plannedEndTime: '08:10',
    plannedDurationMinutes: 10,
    actualStartTime: '08:00',
    actualEndTime: '08:12',
    actualDurationMinutes: 12,
    title: 'Morning Assembly & Staff Briefing',
    description: 'General school assembly and teacher announcements',
    activityType: 'SCHOOL',
    status: 'COMPLETED',
    isMustWin: false,
    remarks: 'Delayed 2 min due to mic setup',
    createdAt: '2026-09-06T22:00:00Z',
  },
  {
    id: 'entry-today-2',
    date: '2026-09-07',
    plannedStartTime: '08:10',
    plannedEndTime: '08:50',
    plannedDurationMinutes: 40,
    actualStartTime: '08:15',
    actualEndTime: '08:52',
    actualDurationMinutes: 37,
    title: 'Zero Period & Attendance Review',
    description: 'Review student attendance registers and MIS updates',
    activityType: 'SCHOOL',
    status: 'COMPLETED',
    sourceType: 'FIXED_COMMITMENT',
    isExternalCommitment: true,
    googleCalendarEventId: 'gcal-school-01',
    googleCalendarId: 'primary',
    syncStatus: 'SYNCED',
    isMustWin: false,
    remarks: 'Quick MIS check completed',
    createdAt: '2026-09-06T22:00:00Z',
  },
  {
    id: 'entry-today-3',
    date: '2026-09-07',
    plannedStartTime: '09:30',
    plannedEndTime: '10:10',
    plannedDurationMinutes: 40,
    actualStartTime: '09:35',
    actualEndTime: '10:20',
    actualDurationMinutes: 45,
    title: 'Meeting: Plato International Coordination',
    description: 'Curriculum alignment and exam schedule discussion',
    activityType: 'MEETING',
    status: 'COMPLETED',
    sourceType: 'FIXED_COMMITMENT',
    isExternalCommitment: true,
    googleCalendarEventId: 'gcal-meeting-02',
    googleCalendarId: 'primary',
    syncStatus: 'SYNCED',
    isMustWin: false,
    remarks: 'Meeting extended 10 min for syllabus review',
    createdAt: '2026-09-06T22:00:00Z',
  },
  {
    id: 'entry-today-4',
    date: '2026-09-07',
    plannedStartTime: '10:10',
    plannedEndTime: '10:50',
    plannedDurationMinutes: 40,
    actualStartTime: '10:25',
    actualEndTime: '10:55',
    actualDurationMinutes: 30,
    title: 'Gift & Certificate Distribution',
    description: 'Hand over academic awards to 9th grade students',
    activityType: 'ADMIN',
    status: 'COMPLETED',
    sourceType: 'FIXED_COMMITMENT',
    isExternalCommitment: true,
    googleCalendarEventId: 'gcal-school-03',
    googleCalendarId: 'primary',
    syncStatus: 'SYNCED',
    isMustWin: false,
    remarks: 'Started 15 min late due to previous meeting',
    createdAt: '2026-09-06T22:00:00Z',
  },
  {
    id: 'entry-today-5',
    date: '2026-09-07',
    plannedStartTime: '11:10',
    plannedEndTime: '11:50',
    plannedDurationMinutes: 40,
    title: 'NLP Meeting & Syllabus Review',
    description: 'Discuss lesson plans and weekly deliverables',
    activityType: 'MEETING',
    status: 'PLANNED',
    sourceType: 'FIXED_COMMITMENT',
    isExternalCommitment: true,
    googleCalendarEventId: 'gcal-meeting-04',
    googleCalendarId: 'primary',
    syncStatus: 'SYNCED',
    isMustWin: false,
    remarks: 'Pending HOD arrival',
    createdAt: '2026-09-06T22:00:00Z',
  },
  {
    id: 'entry-today-6',
    date: '2026-09-07',
    plannedStartTime: '16:00',
    plannedEndTime: '19:00',
    plannedDurationMinutes: 180,
    title: 'Tuition Batches (9th & 10th Math/Science)',
    description: 'Regular coaching batches',
    activityType: 'TUITION',
    status: 'PLANNED',
    sourceType: 'FIXED_COMMITMENT',
    isExternalCommitment: true,
    googleCalendarEventId: 'gcal-tuition-05',
    googleCalendarId: 'primary',
    syncStatus: 'SYNCED',
    isMustWin: false,
    createdAt: '2026-09-06T22:00:00Z',
  },
  {
    id: 'entry-today-7',
    date: '2026-09-07',
    plannedStartTime: '19:00',
    plannedEndTime: '22:30',
    plannedDurationMinutes: 210,
    title: 'Evening Home Tuitions & Classes',
    description: 'Senior secondary coaching sessions',
    activityType: 'CLASSES',
    status: 'PLANNED',
    sourceType: 'FIXED_COMMITMENT',
    isExternalCommitment: true,
    googleCalendarEventId: 'gcal-tuition-06',
    googleCalendarId: 'primary',
    syncStatus: 'SYNCED',
    isMustWin: false,
    createdAt: '2026-09-06T22:00:00Z',
  },
  {
    id: 'entry-today-8',
    date: '2026-09-07',
    plannedStartTime: '22:30',
    plannedEndTime: '23:15',
    plannedDurationMinutes: 45,
    title: 'Dinner & Buffer / Headspace Transition',
    description: 'Decompress, dinner, prepare for CEO Work Block',
    activityType: 'REST',
    status: 'PLANNED',
    sourceType: 'BUFFER',
    isMustWin: false,
    createdAt: '2026-09-06T22:00:00Z',
  },
  {
    id: 'entry-today-9',
    date: '2026-09-07',
    plannedStartTime: '23:15',
    plannedEndTime: '00:00',
    plannedDurationMinutes: 45,
    title: 'Finish Prorido Homepage Hero Section',
    description: 'Build hero section with high-contrast typography and CTAs',
    activityType: 'DESIGNOIA',
    businessCode: 'DESIGNOIA',
    projectId: 'proj-des-prorido',
    taskId: 'task-prorido-home',
    status: 'PLANNED',
    sourceType: 'CEO_OS_TASK',
    googleCalendarEventId: 'gcal-prorido-home-01',
    googleCalendarId: 'primary',
    syncStatus: 'SYNCED',
    isMustWin: true,
    remarks: 'Today\'s Primary Must-Win execution window',
    createdAt: '2026-09-06T22:00:00Z',
  },
  {
    id: 'entry-today-10',
    date: '2026-09-07',
    plannedStartTime: '00:00',
    plannedEndTime: '00:30',
    plannedDurationMinutes: 30,
    title: 'COL Notes 10th Chapter 1 Upload',
    description: 'Verify formula formatting and upload to portal',
    activityType: 'COL',
    businessCode: 'COL',
    projectId: 'proj-col-notes',
    taskId: 'task-col-10th',
    status: 'PLANNED',
    sourceType: 'CEO_OS_TASK',
    isMustWin: false,
    createdAt: '2026-09-06T22:00:00Z',
  },

  // Yesterday's entries (2026-09-06) for comparison and analytics
  {
    id: 'entry-yest-1',
    date: '2026-09-06',
    plannedStartTime: '10:00',
    plannedEndTime: '11:00',
    plannedDurationMinutes: 60,
    actualStartTime: '10:10',
    actualEndTime: '11:05',
    actualDurationMinutes: 55,
    title: 'Sunday Lesson Planning & Weekly Materials',
    activityType: 'PLANNING',
    status: 'COMPLETED',
    isMustWin: false,
    remarks: 'Completed smoothly',
    createdAt: '2026-09-05T22:00:00Z',
  },
  {
    id: 'entry-yest-2',
    date: '2026-09-06',
    plannedStartTime: '17:00',
    plannedEndTime: '19:00',
    plannedDurationMinutes: 120,
    actualStartTime: '17:15',
    actualEndTime: '19:10',
    actualDurationMinutes: 115,
    title: 'Sunday Weekend Tuition Batch',
    activityType: 'TUITION',
    status: 'COMPLETED',
    isMustWin: false,
    createdAt: '2026-09-05T22:00:00Z',
  },
  {
    id: 'entry-yest-3',
    date: '2026-09-06',
    plannedStartTime: '23:15',
    plannedEndTime: '00:00',
    plannedDurationMinutes: 45,
    actualStartTime: '23:20',
    actualEndTime: '23:58',
    actualDurationMinutes: 38,
    title: 'Build hero section with typography',
    activityType: 'DESIGNOIA',
    businessCode: 'DESIGNOIA',
    projectId: 'proj-des-prorido',
    taskId: 'task-prorido-home',
    status: 'COMPLETED',
    isMustWin: true,
    remarks: 'Completed wireframe and hero structure',
    createdAt: '2026-09-05T22:00:00Z',
  }
];

export const INITIAL_SCHEDULE_DAY_REVIEWS: ScheduleDayReview[] = [
  {
    id: 'review-2026-09-06',
    date: '2026-09-06',
    plannedTotalMinutes: 225,
    actualTotalMinutes: 208,
    varianceMinutes: -17,
    planningAccuracyPercent: 92,
    completedBlocksCount: 3,
    missedBlocksCount: 0,
    rescheduledBlocksCount: 0,
    mustWinCompleted: true,
    primaryDifferenceReason: 'OTHER',
    remarks: 'Great Sunday execution. Stayed disciplined on Sunday CEO block.',
    createdAt: '2026-09-06T23:59:00Z',
  }
];

// Initial Google Integration Constants
export const INITIAL_GOOGLE_CONNECTION: GoogleConnection = {
  id: 'conn-demo-01',
  userId: 'user-founder-01',
  googleAccountEmail: 'founder.ceo@gmail.com',
  googleUserId: '109283746501928374',
  scopes: [
    'https://www.googleapis.com/auth/tasks',
    'https://www.googleapis.com/auth/calendar.events',
    'https://www.googleapis.com/auth/userinfo.email',
  ],
  status: 'CONNECTED',
  isTasksEnabled: true,
  isCalendarEnabled: true,
  primaryCalendarId: 'primary',
  selectedCalendarIds: ['primary'],
  defaultTaskListId: 'list-inbox',
  syncIntervalMinutes: 5,
  lastSyncAt: '2026-09-07T08:00:00Z',
  createdAt: '2026-09-01T00:00:00Z',
  updatedAt: '2026-09-07T08:00:00Z',
};

export const INITIAL_TASK_LIST_MAPPINGS: GoogleTaskListMapping[] = [
  { taskListId: 'list-inbox', taskListTitle: 'My Tasks', isInboxDefault: true },
  { taskListId: 'list-col', taskListTitle: 'COL', businessCode: 'COL' },
  { taskListId: 'list-designoia', taskListTitle: 'Designoia', businessCode: 'DESIGNOIA' },
  { taskListId: 'list-prorido', taskListTitle: 'Prorido', businessCode: 'DESIGNOIA', projectId: 'proj-prorido-web' },
  { taskListId: 'list-clikixpress', taskListTitle: 'Clikixpress', businessCode: 'CLIKIXPRESS' },
  { taskListId: 'list-personal', taskListTitle: 'Personal', businessCode: 'PERSONAL' },
  { taskListId: 'list-school', taskListTitle: 'School', businessCode: 'PERSONAL' },
];

export const INITIAL_GOOGLE_TASK_MAPPINGS: GoogleTaskMapping[] = [
  {
    id: 'gtmap-01',
    userId: 'user-founder-01',
    ceoTaskId: 'task-prorido-home',
    googleTaskId: 'gtask-prorido-home-01',
    googleTaskListId: 'list-prorido',
    googleEtag: '"etag-gtask-01"',
    lastGoogleUpdatedAt: '2026-09-07T08:00:00Z',
    lastCeoUpdatedAt: '2026-09-07T08:00:00Z',
    syncStatus: 'SYNCED',
  },
  {
    id: 'gtmap-02',
    userId: 'user-founder-01',
    ceoTaskId: 'task-gt-pagespeed',
    googleTaskId: 'gtask-pagespeed-02',
    googleTaskListId: 'list-prorido',
    googleEtag: '"etag-gtask-02"',
    lastGoogleUpdatedAt: '2026-09-07T08:00:00Z',
    lastCeoUpdatedAt: '2026-09-07T08:00:00Z',
    syncStatus: 'SYNCED',
  },
  {
    id: 'gtmap-03',
    userId: 'user-founder-01',
    ceoTaskId: 'task-gt-supplier-call',
    googleTaskId: 'gtask-supplier-03',
    googleTaskListId: 'list-clikixpress',
    googleEtag: '"etag-gtask-03"',
    lastGoogleUpdatedAt: '2026-09-07T08:00:00Z',
    lastCeoUpdatedAt: '2026-09-07T08:00:00Z',
    syncStatus: 'SYNCED',
  },
];

export const INITIAL_GOOGLE_CALENDAR_MAPPINGS: GoogleCalendarMapping[] = [
  {
    id: 'gcmap-01',
    userId: 'user-founder-01',
    ceoTaskId: 'task-prorido-home',
    scheduleEntryId: 'entry-today-9',
    calendarId: 'primary',
    googleEventId: 'gcal-prorido-home-01',
    googleEventEtag: '"etag-gcal-01"',
    lastGoogleUpdatedAt: '2026-09-07T08:00:00Z',
    lastCeoUpdatedAt: '2026-09-07T08:00:00Z',
    syncStatus: 'SYNCED',
  },
];

export const INITIAL_GOOGLE_SYNC_LOGS: GoogleSyncLog[] = [
  {
    id: 'log-seed-01',
    eventType: 'SYNC_COMPLETED',
    details: 'Initial synchronization completed. 3 Google Tasks linked, 5 Google Calendar commitments imported.',
    createdAt: '2026-09-07T08:00:00Z',
  },
  {
    id: 'log-seed-02',
    eventType: 'GOOGLE_TASK_IMPORTED',
    details: 'Imported from Google Tasks: "Check Prorido PageSpeed"',
    entityId: 'task-gt-pagespeed',
    entityTitle: 'Check Prorido PageSpeed',
    createdAt: '2026-09-07T07:45:00Z',
  },
  {
    id: 'log-seed-03',
    eventType: 'GOOGLE_EVENT_CREATED',
    details: 'Scheduled CEO OS task in Google Calendar: "Finish Prorido Homepage" (23:15–00:00)',
    entityId: 'entry-today-9',
    entityTitle: 'Finish Prorido Homepage',
    createdAt: '2026-09-06T22:00:00Z',
  },
];

