import { Business, Goal, StrategicMonth, Project, Task, ScheduleBlock, UserSettings } from './types';

export const INITIAL_BUSINESSES: Business[] = [
  {
    id: 'biz-col',
    code: 'COL',
    name: 'Circle of Learning',
    tagline: 'Education & Institutional Scale',
    description: 'Notes, tests, institutional expansion, digital presence, and education engines.',
    color: '#3b82f6', // Blue
    iconName: 'GraduationCap',
    isActive: true,
  },
  {
    id: 'biz-designoia',
    code: 'DESIGNOIA',
    name: 'Designoia',
    tagline: 'Design Agency & Sales Engine',
    description: 'Digital presence, international outreach, premium client acquisition, and creative studio.',
    color: '#8b5cf6', // Purple
    iconName: 'Sparkles',
    isActive: true,
  },
  {
    id: 'biz-clikixpress',
    code: 'CLIKIXPRESS',
    name: 'Clikixpress',
    tagline: 'Ecommerce & Logistics Scale',
    description: 'Pvt Ltd entity, ecommerce platform, manufacturing, godowns, and fulfillment network.',
    color: '#f97316', // Orange
    iconName: 'Package',
    isActive: true,
  },
  {
    id: 'biz-personal',
    code: 'PERSONAL',
    name: 'Personal',
    tagline: 'Life, Assets & Well-being',
    description: 'Car, home, health, personal assets, and family milestones.',
    color: '#10b981', // Emerald
    iconName: 'User',
    isActive: true,
  },
];

export const INITIAL_GOALS: Goal[] = [
  // COL Goals
  {
    id: 'goal-col-1',
    businessCode: 'COL',
    title: '5 Physical Institutes',
    category: 'infrastructure',
    targetYear: 2029,
    targetMetric: '5 centers',
    currentMetric: '1 center developing',
    isCompleted: false,
  },
  {
    id: 'goal-col-2',
    businessCode: 'COL',
    title: '₹5 Lakh / Month Recurring Revenue',
    category: 'revenue',
    targetYear: 2028,
    targetMetric: '₹5,00,000 / mo',
    currentMetric: '₹0 / mo',
    isCompleted: false,
  },
  {
    id: 'goal-col-3',
    businessCode: 'COL',
    title: 'COL Digital Learning Platform & International Reach',
    category: 'scale',
    targetYear: 2028,
    targetMetric: 'Global enrolled students',
    currentMetric: 'Phase 1 development',
    isCompleted: false,
  },
  {
    id: 'goal-col-4',
    businessCode: 'COL',
    title: 'YouTube Channel: 100,000 Subscribers & Monetization',
    category: 'audience',
    targetYear: 2027,
    targetMetric: '100k subs + revenue',
    currentMetric: 'Channel setup',
    isCompleted: false,
  },

  // Designoia Goals
  {
    id: 'goal-des-1',
    businessCode: 'DESIGNOIA',
    title: 'High-Converting Digital Presence & Case Study Portfolio',
    category: 'system',
    targetYear: 2026,
    targetMetric: 'Active client pipeline',
    currentMetric: 'Portfolio development',
    isCompleted: false,
  },
  {
    id: 'goal-des-2',
    businessCode: 'DESIGNOIA',
    title: 'International Client Roster (US/UK/EU/Middle East)',
    category: 'revenue',
    targetYear: 2027,
    targetMetric: '5 recurring retainer clients',
    currentMetric: 'Prospect lists initiated',
    isCompleted: false,
  },
  {
    id: 'goal-des-3',
    businessCode: 'DESIGNOIA',
    title: 'Physical Creative Studio / Office in Noida / Gurgaon',
    category: 'infrastructure',
    targetYear: 2029,
    targetMetric: 'Dedicated office lease',
    currentMetric: 'Virtual',
    isCompleted: false,
  },
  {
    id: 'goal-des-4',
    businessCode: 'DESIGNOIA',
    title: 'Well-Trained Elite Creative & Growth Team',
    category: 'scale',
    targetYear: 2028,
    targetMetric: '6 full-time specialists',
    currentMetric: 'Solo founder',
    isCompleted: false,
  },

  // Clikixpress Goals
  {
    id: 'goal-clk-1',
    businessCode: 'CLIKIXPRESS',
    title: 'Incorporate Pvt Ltd Company & Regulatory Compliance',
    category: 'infrastructure',
    targetYear: 2027,
    targetMetric: 'Certificate of Incorporation',
    currentMetric: 'MSME registration',
    isCompleted: false,
  },
  {
    id: 'goal-clk-2',
    businessCode: 'CLIKIXPRESS',
    title: 'Proprietary Ecommerce Platform & Mobile App',
    category: 'system',
    targetYear: 2027,
    targetMetric: 'Web + iOS + Android live',
    currentMetric: 'Architecture phase',
    isCompleted: false,
  },
  {
    id: 'goal-clk-3',
    businessCode: 'CLIKIXPRESS',
    title: 'Owned Godowns, Warehouses & Dedicated Logistics Staff',
    category: 'infrastructure',
    targetYear: 2030,
    targetMetric: '2 fulfillment centers',
    currentMetric: 'Initial planning',
    isCompleted: false,
  },
  {
    id: 'goal-clk-4',
    businessCode: 'CLIKIXPRESS',
    title: 'In-House Manufacturing & Global Cross-Border Expansion',
    category: 'scale',
    targetYear: 2031,
    targetMetric: 'Global shipping active',
    currentMetric: 'Research',
    isCompleted: false,
  },

  // Personal Goals
  {
    id: 'goal-per-1',
    businessCode: 'PERSONAL',
    title: 'Acquire First Premium Car',
    category: 'personal',
    targetYear: 2028,
    targetMetric: 'Car purchased outright/comfortably financed',
    currentMetric: 'Savings plan',
    isCompleted: false,
  },
  {
    id: 'goal-per-2',
    businessCode: 'PERSONAL',
    title: 'Purchase Dream Home Property',
    category: 'personal',
    targetYear: 2030,
    targetMetric: 'Deed registration',
    currentMetric: 'Financial roadmap',
    isCompleted: false,
  },
  {
    id: 'goal-per-3',
    businessCode: 'PERSONAL',
    title: 'Full Financial Freedom & Exit School/Tuition Schedule',
    category: 'personal',
    targetYear: 2028,
    targetMetric: '100% full-time on ventures',
    currentMetric: 'Transitioning',
    isCompleted: false,
  },
];

export const INITIAL_STRATEGIC_MONTHS: StrategicMonth[] = [
  {
    id: 'm-2026-09',
    yearMonth: '2026-09',
    focusTitle: 'Foundation + Master Plan + Systems',
    targetOutcome: 'Complete core operational setup, notes upload pipeline, and initial n8n automation links.',
    kpis: ['CEO OS deployed & daily active', 'COL Notes 9th & 10th ready', 'FB & Pinterest workflows tested'],
    definitionOfDone: 'All foundational digital assets configured, daily 45-min execution habit established.',
    isCurrent: true,
  },
  {
    id: 'm-2026-10',
    yearMonth: '2026-10',
    focusTitle: 'Designoia Digital Presence',
    targetOutcome: 'Launch high-converting agency portfolio and initial offer packaging.',
    kpis: ['Designoia landing page live', '3 polished case studies published', 'Cold outreach list ready'],
    definitionOfDone: 'Live URL with client booking integration and tested submission flow.',
  },
  {
    id: 'm-2026-11',
    yearMonth: '2026-11',
    focusTitle: 'Designoia Sales Engine',
    targetOutcome: 'Initiate international outreach campaign and secure first consultation calls.',
    kpis: ['100 targeted DMs/emails sent', '5 discovery calls booked', '1 retainer proposal sent'],
    definitionOfDone: 'Sales outreach SOP tested and repeatable.',
  },
  {
    id: 'm-2026-12',
    yearMonth: '2026-12',
    focusTitle: 'COL Systems & Content Pipeline',
    targetOutcome: 'Standardize test generation, NCERT solutions, and content publishing workflow.',
    kpis: ['11th and 12th Notes uploaded', 'Automated test bank active', 'Video recording schedule set'],
    definitionOfDone: 'COL educational resources accessible and organized for distribution.',
  },
  {
    id: 'm-2027-01',
    yearMonth: '2027-01',
    focusTitle: 'Clikixpress MVP',
    targetOutcome: 'Define initial product catalogue, supplier terms, and web storefront prototype.',
    kpis: ['Product shortlist locked', 'Supplier agreements drafted', 'Shopify/custom storefront MVP ready'],
    definitionOfDone: 'First end-to-end test checkout successfully placed.',
  },
  {
    id: 'm-2027-02',
    yearMonth: '2027-02',
    focusTitle: 'Automation Month',
    targetOutcome: 'Link n8n workflows for lead nurturing, social auto-posting, and order routing.',
    kpis: ['Cross-platform posting active', 'Lead auto-capture to CRM', 'Alerts on high-priority inquiries'],
    definitionOfDone: 'Zero manual copy-pasting for inquiries and basic social distribution.',
  },
  {
    id: 'm-2027-03',
    yearMonth: '2027-03',
    focusTitle: 'Content Engine',
    targetOutcome: 'Launch YouTube educational channel and organic agency reels.',
    kpis: ['8 long-form videos published', '16 short-form reels', '1,000 subscribers reached'],
    definitionOfDone: 'Consistent weekly publishing cadence running.',
  },
  {
    id: 'm-2027-04',
    yearMonth: '2027-04',
    focusTitle: 'Team Foundation',
    targetOutcome: 'Hire first freelance editor / VA to delegate non-core tasks.',
    kpis: ['Job description published', 'Candidate hired & trained', 'SOP library created'],
    definitionOfDone: 'First 10 hours/week of routine work delegated.',
  },
  {
    id: 'm-2027-05',
    yearMonth: '2027-05',
    focusTitle: 'Revenue Push',
    targetOutcome: 'Target ₹1.5L/mo combined profit run-rate across active ventures.',
    kpis: ['Designoia monthly revenue > ₹1L', 'COL enrollments active', 'Clikixpress initial sales'],
    definitionOfDone: 'Clear cash flow buffer established in business account.',
  },
  {
    id: 'm-2027-06',
    yearMonth: '2027-06',
    focusTitle: 'Finance + Compliance',
    targetOutcome: 'Complete tax planning, GST filings, and formal accounting structure.',
    kpis: ['Chartered Accountant review', 'GST filing streamlined', 'Clean P&L dashboard'],
    definitionOfDone: 'All corporate filings up to date with zero compliance backlogs.',
  },
  {
    id: 'm-2027-07',
    yearMonth: '2027-07',
    focusTitle: 'Scale Readiness',
    targetOutcome: 'Stress-test infrastructure, server capacity, and fulfillment logistics.',
    kpis: ['Load test web services', 'Fulfillment turnaround < 48hrs', 'Customer satisfaction > 90%'],
    definitionOfDone: 'Ready to handle 5x user volume without breaking.',
  },
  {
    id: 'm-2027-08',
    yearMonth: '2027-08',
    focusTitle: 'Annual Review & Year 2 Strategy',
    targetOutcome: 'Comprehensive 360 review of Year 1 achievements and Year 2 calibration.',
    kpis: ['Annual targets vs actuals audited', '5-year vision refreshed', 'Year 2 roadmap approved'],
    definitionOfDone: 'Year 2 Q1-Q4 roadmap fully mapped in CEO OS.',
  },
  // Years 2027-2031 generated milestones
  {
    id: 'm-2027-09',
    yearMonth: '2027-09',
    focusTitle: 'Year 2: Institutional Expansion (COL Institute 1)',
    targetOutcome: 'Open first dedicated physical center for Circle of Learning.',
    kpis: ['Location secured', 'Initial batch enrolled', 'Local marketing blitz'],
    definitionOfDone: 'Physical center operating with positive unit economics.',
  },
  {
    id: 'm-2028-01',
    yearMonth: '2028-01',
    focusTitle: 'Clikixpress Mobile App Launch',
    targetOutcome: 'Publish Clikixpress mobile application on App Store & Play Store.',
    kpis: ['App approved', '5,000 downloads', '4.5+ star rating'],
    definitionOfDone: 'App-driven orders exceed 40% of total revenue.',
  },
  {
    id: 'm-2028-09',
    yearMonth: '2028-09',
    focusTitle: 'Year 3: Full Freedom Transition',
    targetOutcome: 'Step down from school/tuition commitments to lead ventures 100% full-time.',
    kpis: ['Recurring business income > 4x job salary', 'Complete time independence'],
    definitionOfDone: 'Full-time CEO schedule unlocked.',
  },
  {
    id: 'm-2029-09',
    yearMonth: '2029-09',
    focusTitle: 'Year 4: Multi-City Agency & Institute Scale',
    targetOutcome: 'Open Designoia studio in Noida/Gurgaon and expand COL to 3+ centers.',
    kpis: ['Office operational', 'COL 3 centers', 'Enterprise client contracts'],
    definitionOfDone: 'Dedicated management layer handling operations.',
  },
  {
    id: 'm-2030-09',
    yearMonth: '2030-09',
    focusTitle: 'Year 5: Clikixpress Godowns & Global Expansion',
    targetOutcome: 'Commission owned warehouse hubs and initiate cross-border logistics.',
    kpis: ['Owned warehouse operational', 'International orders shipping', 'Asset milestone reached'],
    definitionOfDone: 'Complete 5-year master plan realized.',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-p001',
    code: 'P-001',
    name: 'COL Automations',
    businessCode: 'COL',
    monthYear: '2026-09',
    description: 'Social media, lead capture, and distribution workflows via n8n.',
    successDefinition: 'All required social media automation workflows (FB, Pinterest, YouTube) are connected, verified, and running without manual intervention.',
    status: 'ACTIVE',
    priority: 'P1',
    startDate: '2026-09-01',
    targetDate: '2026-09-30',
    createdAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'proj-p002',
    code: 'P-002',
    name: 'COL Notes',
    businessCode: 'COL',
    monthYear: '2026-09',
    description: 'Curriculum-aligned study notes and digital downloads.',
    successDefinition: 'All required 9th, 10th, 11th, and 12th notes are cleanly formatted, converted to PDF, uploaded, and downloadable by students.',
    status: 'ACTIVE',
    priority: 'P1',
    startDate: '2026-09-01',
    targetDate: '2026-09-25',
    createdAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'proj-p003',
    code: 'P-003',
    name: 'COL Tests',
    businessCode: 'COL',
    monthYear: '2026-09',
    description: 'Chapter-wise and full mock test series for secondary and competitive exams.',
    successDefinition: 'Structured test papers and automated answer keys are created, proofread, and ready for batch evaluation.',
    status: 'ACTIVE',
    priority: 'P2',
    startDate: '2026-09-15',
    targetDate: '2026-10-15',
    createdAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'proj-p004',
    code: 'P-004',
    name: 'Skill Courses',
    businessCode: 'COL',
    monthYear: '2026-10',
    description: 'Practical vocational and digital skill mini-certifications.',
    successDefinition: 'Curriculum outline and pilot modules for first 2 high-demand skill courses recorded and uploaded.',
    status: 'ACTIVE',
    priority: 'P3',
    startDate: '2026-10-01',
    targetDate: '2026-10-31',
    createdAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'proj-p005',
    code: 'P-005',
    name: 'Designoia Digital Engine',
    businessCode: 'DESIGNOIA',
    monthYear: '2026-10',
    description: 'Agency portfolio, case studies, and international client acquisition funnel.',
    successDefinition: 'Landing page deployed, 10 international prospect accounts researched and initial outreach launched.',
    status: 'ACTIVE',
    priority: 'P1',
    startDate: '2026-10-01',
    targetDate: '2026-10-31',
    createdAt: '2026-09-01T00:00:00Z',
  }
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-t001',
    code: 'T-001',
    title: 'Connect FB to n8n',
    businessCode: 'COL',
    projectId: 'proj-p001',
    status: 'TODAY',
    priority: 'P1',
    isMustWin: false,
    estimatedMinutes: 30,
    scheduledDate: '2026-09-05',
    scheduledTime: '23:15',
    notes: 'Verify OAuth permissions in Meta developer console and test webhook.',
    rescueAction: 'Check FB developer token validity and test one ping in n8n.',
    createdAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'task-t002',
    code: 'T-002',
    title: 'Connect Pinterest to n8n',
    businessCode: 'COL',
    projectId: 'proj-p001',
    status: 'TODAY',
    priority: 'P1',
    isMustWin: false,
    estimatedMinutes: 25,
    scheduledDate: '2026-09-05',
    notes: 'Configure Pinterest board token and automated pin creation node.',
    rescueAction: 'Log into Pinterest business account and copy board ID.',
    createdAt: '2026-09-01T10:05:00Z',
  },
  {
    id: 'task-t003',
    code: 'T-003',
    title: 'Hindi YouTube videos setup',
    businessCode: 'COL',
    projectId: 'proj-p001',
    status: 'TODAY',
    priority: 'P1',
    isMustWin: false,
    estimatedMinutes: 35,
    scheduledDate: '2026-09-05',
    notes: 'Outline video structure and prepare YouTube thumbnail template.',
    rescueAction: 'Draft 3 catchy Hindi video titles in notes.',
    createdAt: '2026-09-01T10:10:00Z',
  },
  {
    id: 'task-t004',
    code: 'T-004',
    title: '9th notes preparation',
    businessCode: 'COL',
    projectId: 'proj-p002',
    status: 'THIS_WEEK',
    priority: 'P1',
    estimatedMinutes: 45,
    notes: 'Compile Science & Math chapters 1-4 summaries.',
    rescueAction: 'Review Chapter 1 summary bullet points.',
    createdAt: '2026-09-01T10:15:00Z',
  },
  {
    id: 'task-t005',
    code: 'T-005',
    title: 'Finish 10th Notes',
    businessCode: 'COL',
    projectId: 'proj-p002',
    status: 'TODAY',
    priority: 'P1',
    isMustWin: true, // PRIMARY MUST-WIN
    estimatedMinutes: 45,
    scheduledDate: '2026-09-05',
    scheduledTime: '23:15',
    notes: 'Export PDF, verify formula formatting in Physics & Chemistry chapters, and upload to digital folder.',
    rescueAction: 'Check formatting on first 5 pages of 10th Science PDF and export.',
    createdAt: '2026-09-01T10:20:00Z',
  },
  {
    id: 'task-t006',
    code: 'T-006',
    title: '11th notes compilation',
    businessCode: 'COL',
    projectId: 'proj-p002',
    status: 'THIS_WEEK',
    priority: 'P2',
    estimatedMinutes: 45,
    notes: 'Organize core concepts and NCERT highlights.',
    rescueAction: 'Index chapter titles for Class 11 Physics.',
    createdAt: '2026-09-01T10:25:00Z',
  },
  {
    id: 'task-t007',
    code: 'T-007',
    title: '12th notes compilation',
    businessCode: 'COL',
    projectId: 'proj-p002',
    status: 'THIS_WEEK',
    priority: 'P2',
    estimatedMinutes: 45,
    notes: 'Review board exam focus areas.',
    rescueAction: 'Draft chapter 1 key formula list.',
    createdAt: '2026-09-01T10:30:00Z',
  },
  {
    id: 'task-t008',
    code: 'T-008',
    title: 'MSME Registration',
    businessCode: 'COL',
    projectId: 'proj-p001',
    status: 'TODAY',
    priority: 'P1',
    isMustWin: false,
    estimatedMinutes: 30,
    scheduledDate: '2026-09-05',
    notes: 'Fill Udyam registration portal details with Aadhaar verification.',
    rescueAction: 'Verify Aadhaar OTP portal readiness and document checklist.',
    createdAt: '2026-09-01T10:35:00Z',
  },
  {
    id: 'task-t009',
    code: 'T-009',
    title: 'FB app verification',
    businessCode: 'COL',
    projectId: 'proj-p001',
    status: 'TODAY',
    priority: 'P1',
    isMustWin: false,
    estimatedMinutes: 30,
    scheduledDate: '2026-09-05',
    notes: 'Submit privacy policy URL and business use-case video.',
    rescueAction: 'Verify privacy policy URL is reachable.',
    createdAt: '2026-09-01T10:40:00Z',
  },
  {
    id: 'task-t010',
    code: 'T-010',
    title: 'NCERT solutions review',
    businessCode: 'COL',
    projectId: 'proj-p002',
    status: 'THIS_WEEK',
    priority: 'P2',
    estimatedMinutes: 40,
    notes: 'Ensure step-by-step solutions match current syllabus.',
    rescueAction: 'Check solutions for 3 sample questions.',
    createdAt: '2026-09-01T10:45:00Z',
  },
  {
    id: 'task-t011',
    code: 'T-011',
    title: 'JEE Notes planning',
    businessCode: 'COL',
    projectId: 'proj-p002',
    status: 'NEXT',
    priority: 'P3',
    estimatedMinutes: 60,
    notes: 'Curate high-yield formulas and previous year questions.',
    rescueAction: 'List top 5 high-weightage JEE topics.',
    createdAt: '2026-09-01T10:50:00Z',
  },
  {
    id: 'task-t012',
    code: 'T-012',
    title: 'JEE Tests creation',
    businessCode: 'COL',
    projectId: 'proj-p003',
    status: 'NEXT',
    priority: 'P3',
    estimatedMinutes: 60,
    notes: 'Format 30-question mock test papers.',
    rescueAction: 'Draft 5 questions for Physics module.',
    createdAt: '2026-09-01T10:55:00Z',
  },
  {
    id: 'task-t013',
    code: 'T-013',
    title: 'NEET Notes structure',
    businessCode: 'COL',
    projectId: 'proj-p002',
    status: 'NEXT',
    priority: 'P3',
    estimatedMinutes: 60,
    notes: 'Biology diagrams and mnemonics list.',
    rescueAction: 'Outline Botany unit 1 mnemonics.',
    createdAt: '2026-09-01T11:00:00Z',
  },
  {
    id: 'task-t014',
    code: 'T-014',
    title: 'NEET Tests structure',
    businessCode: 'COL',
    projectId: 'proj-p003',
    status: 'NEXT',
    priority: 'P3',
    estimatedMinutes: 60,
    notes: 'Prepare NEET mock series 1.',
    rescueAction: 'Review syllabus weightage breakdown.',
    createdAt: '2026-09-01T11:05:00Z',
  },
  {
    id: 'task-t015',
    code: 'T-015',
    title: 'Skill Courses outline',
    businessCode: 'COL',
    projectId: 'proj-p004',
    status: 'NEXT',
    priority: 'P3',
    estimatedMinutes: 45,
    notes: 'Draft lesson plan for first digital marketing and design mini-course.',
    rescueAction: 'Write 4 module titles for digital design skills.',
    createdAt: '2026-09-01T11:10:00Z',
  },
];

export const INITIAL_SCHEDULE_BLOCKS: ScheduleBlock[] = [
  {
    id: 'sched-1',
    name: 'School / MIS / Admin',
    startTime: '08:00',
    endTime: '16:00',
    category: 'SCHOOL',
    daysOfWeek: [1, 2, 3, 4, 5, 6],
    isCeoTime: false,
    description: 'Day job responsibilities, MIS coordination, and administration.',
  },
  {
    id: 'sched-2',
    name: 'Tuition Classes',
    startTime: '16:00',
    endTime: '19:00',
    category: 'TUITION',
    daysOfWeek: [1, 2, 3, 4, 5, 6],
    isCeoTime: false,
    description: 'Teaching tuition batches.',
  },
  {
    id: 'sched-3',
    name: 'Home Tuition / Evening Classes',
    startTime: '19:00',
    endTime: '22:30',
    category: 'CLASSES',
    daysOfWeek: [1, 2, 3, 4, 5, 6],
    isCeoTime: false,
    description: 'Evening academic batches and student sessions.',
  },
  {
    id: 'sched-4',
    name: 'Dinner & Decompress',
    startTime: '22:30',
    endTime: '23:15',
    category: 'REST',
    daysOfWeek: [1, 2, 3, 4, 5, 6, 7],
    isCeoTime: false,
    description: 'Dinner, rest, transition to CEO headspace.',
  },
  {
    id: 'sched-5',
    name: '🚀 CEO Work Block',
    startTime: '23:15',
    endTime: '00:00',
    category: 'CEO_BLOCK',
    daysOfWeek: [1, 2, 3, 4, 5, 6, 7],
    isCeoTime: true,
    description: '30-45 minutes of laser-focused business building & execution.',
  },
];

export const INITIAL_SETTINGS: UserSettings = {
  userName: 'Founder',
  theme: 'dark',
  morningNotificationTime: '07:30',
  ceoBlockStart: '23:15',
  ceoBlockEnd: '00:00',
  defaultWorkDuration: 45,
  rescueModeDuration: 10,
  notificationsEnabled: true,
  audioChimeEnabled: true,
  lastActiveDate: '2026-09-05',
  lastMustWinId: 'task-t005',
  onboardingCompleted: true,
};
